### PR TITLE
Database support

### PR DESCRIPTION
**Pull request by PeachesMLG**
I Thought saving if the scoreboard is on or off for a player in the config was a bit dumb, so I added support to sql databases.

Not Sure if this is overkill or not, but if your planning on adding any more settings for players this will be alot better than saving in config.

### CODE REVIEW

**Comment by joserodpt** [comment]
But wont it be demanding for a server to request information about a player if the player turned on or off the scoreboard, every refresh interval?

**Comment by PeachesMLG** [comment]
Well by default it gets it from a local sqllite database and it also gets this async, however I guess I could add some cache if u want

**Comment by joserodpt** [comment]
Well that could improve the performance i think, dont you agree?
The ScoreboardTask is async already, but it can be improved with that cache i think

**Comment by PeachesMLG** [comment]
Sure ill do this now

**Comment by joserodpt** [comment]
Ok thanks! Commit when you´re done

**Comment by PeachesMLG** [comment]
Completly offtopic, but just so your aware your Discord link on the spigot page is invalid :P

**Comment by joserodpt** [comment]
Is https://github.com/JoseGamerPT/RealScoreboard/pull/11/commits/d07a19925a227c599a3084f46ef8f7f4f04b14f4 async or sync?

**Comment by PeachesMLG** [comment]
Creating the table is executed once during on enable sync

**Comment by joserodpt** [comment]
but everything else is async and with cache, right?
I am not a pro in databases and SQL, sorry

**Comment by PeachesMLG** [comment]
So currently on enable it does the following sync:
Create table
Get all info from the db and puts it in a hashmap for cache

Then while getting data from the db it just gets it from the hashmap cache which is also done sync since it doesnt go to the db.

then saving stuff to the db is done async.

So the only time the db is accessed sync is during onEnable so it shouldnt be an issue

**Comment by joserodpt** [comment]
Ok i will test it thanks

**Pull request merged**
